updated

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -51,42 +51,42 @@ jobs:
             ${{ secrets.DOCKER_HUB_USERNAME }}/student:latest
             ${{ secrets.DOCKER_HUB_USERNAME }}/student:${{ steps.image_tag.outputs.image_tag }}
 
-  deploy-to-ArgoCD:
-    runs-on: ubuntu-latest
-    name: Deploy to ArgoCD
+    deploy-to-argocd:
+    runs-on: self-hosted
+    name: Deploy to Argo CD
     needs: build-and-push
+
+    permissions:
+      contents: write
+
+    env:
+      KUBECONFIG: /home/docker/.kube/config
+
     steps:
       - name: 1. Checkout Repository
         uses: actions/checkout@v4
 
-      - name: 2. List files in the repository (for debugging)
+      - name: 2. Check Kubernetes Connection
         run: |
-          echo "Current directory: $(pwd)"
-          echo "Listing all files..."
-          ls -R .
+          echo "Runner user: $(whoami)"
+          echo "Kubeconfig: ${KUBECONFIG}"
 
-      - name: 4. Update application with new Image Tag
-        run: |
-          sed -i "s|__IMAGE_NAME__|${{ env.DOCKER_IMAGE }}:${{ needs.build-and-push.outputs.image_tag }}|g" argoCD/application.yaml
-          echo "--- Updated application.yaml (application.yaml) ---"
-          cat argoCD/application.yaml
+          test -f "${KUBECONFIG}" || {
+            echo "ERROR: ${KUBECONFIG} does not exist"
+            exit 1
+          }
 
-      - name: 3. Apply Application File
+          kubectl config use-context kind-three-node-cluster
+          kubectl cluster-info
+          kubectl get nodes
+
+      - name: 3. Apply Argo CD Application
         run: |
           kubectl apply -f argoCD/application.yaml
 
-      - name: 4. Check Argo CD Applications
+      - name: 4. Check Resources
         run: |
           kubectl get applications -n argocd
-
-      - name: 5. Check Deployments
-        run: |
           kubectl get deployments
-
-      - name: 6. Check Services
-        run: |
           kubectl get services
-
-      - name: 7. Check Nodes
-        run: |
           kubectl get nodes -o wide
